Use .env mode files, and kirby in subfolder
johannschopplich/kirby-vue3-starterkit pull request #51
Opened 2022-09-25 07:42 UTC by Small-Systems

1. Reformatting of vite.config so that .env mode files can be loaded, using loadEnv from Vite, rather than dotenv.
2. Modified VueKit.php; changed the url returned in the functions assetProd, preloadJson, preloadModule.

The purpose of 2, is that when kirby is in a subfolder the urls will resolve correctly. This is not specific to your install, but I have kirby running in a subfolder on my testing server i.e; dev.domain.com/project.

2022-10-09 18:53 UTC, johannschopplich commented
Great PR! Can you look at the two comments, please? Thanks in advance.

2022-10-10 08:27 UTC, Small-Systems commented
Hi, I don't see any comments, where should I be looking? (I've never done a PR before) Thanks, Luke

2022-10-10 09:22 UTC, johannschopplich commented
You should see them above, related to the code changes:

![grafik](https://user-images.githubusercontent.com/27850750/194834929-d17c3390-5a3d-4bd9-8e67-c43314bf60a1.png)

2022-10-10 09:31 UTC, Small-Systems commented
That's weird, my conversation looks like this:

<img width="742" alt="Screenshot 2022-10-10 at 11 30 08" src="https://user-images.githubusercontent.com/2116283/194836497-b251ab7b-1d0d-4670-b4ce-33725c061cf8.png">

2022-10-10 09:32 UTC, johannschopplich requested changes

2022-10-10 09:32 UTC, johannschopplich commented
My bad, didn't request the review…

2022-11-18 18:35 UTC, johannschopplich commented
Hi there, I have manually merged your feature in https://github.com/johannschopplich/kirby-vue3-starterkit/commit/7e4c385e658c10c5781b195e11b9b92cafc28132, because your feature to deploy Kirby in a subfolder is a separate PR and will have to be tested thoroughly, so it won't break existing installations. Would you mind creating a new PR, thanks in advance!

2022-12-13 13:30 UTC, closed without merging